### ISSUE TITLE
Enable strict mode

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next-hello-world#15]
I am strongly proposing to enable TypeScript's `strict` mode by adding `"strict": true` to `compilerOptions` in `tsconfig.json`. See https://www.typescriptlang.org/docs/handbook/compiler-options.html

> Enable all strict type checking options. 
> Enabling `--strict` enables `--noImplicitAny`, `--noImplicitThis`, `--alwaysStrict` and `--strictNullChecks`.

Note that this change will most likely uncover problems in the code base that we will need to fix before landing this change.

**Comment by Setogit** [comment]
implemented in https://github.com/strongloop/loopback-next-hello-world/pull/13

**Comment by bajtos** [comment]
@Setogit In our process, we close issues only after the pull request(s) have been landed. I am reopening this issue.

**Comment by Setogit** [comment]
:+1

**Comment by Setogit** [comment]
The fix has been merged. Closing.
